# src/main/resources/application.yml
server:
  port: 8068

spring:
  application:
    name: PlayFootball

  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false                       # 콘솔에 SQL문 출력 , # Hibernate랑 중복되어 표시되기 때문에 끔
    properties:
      hibernate:
        format_sql: true                # 보기 좋게 포맷팅된 SQL
  # 엔티티와 트랜잭션 간 충돌 방지용 (선택)
  # open-in-view: false

logging:
  level:
    root: info
    com.zaxxer.hikari: warn
    com.zaxxer.hikari.HikariConfig: warn
    com.p6spy: debug               # p6spy 로그만 debug
    org.hibernate: warn            # Hibernate 로그는 안 찍어도 됨

decorator:
  datasource:
    p6spy:
      enable-logging: true