# src/main/resources/spy.properties

#logMessageFormat=com.p6spy.engine.spy.appender.MultiLineFormat

# \uB610\uB294 \uBCF4\uAE30 \uC88B\uAC8C \uD3EC\uB9F7\uD558\uACE0 \uC2F6\uB2E4\uBA74 \uC544\uB798 \uD3EC\uB9F7 \uC0AC\uC6A9!
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=\n====== [\uCFFC\uB9AC \uC2DC\uC791~!~!] ======\n%(sql)\n====== [\uCFFC\uB9AC \uB05D~!~!] ======\n

# \uBC14\uC778\uB529\uB41C \uAC12 \uD3EC\uD568
includeBindings=false

# \uB85C\uADF8 \uCC0D\uD788\uB294 \uB300\uC0C1
appender=com.p6spy.engine.spy.appender.Slf4JLogger



